import Foundation

struct TeamInfo {
    let zh: String
    let flag: String
}

enum Teams {
    static func info(_ name: String) -> TeamInfo {
        map[name] ?? TeamInfo(zh: name, flag: "⚽️")
    }

    static let map: [String: TeamInfo] = [
        // football-data.org 队名写法
        "Cape Verde Islands": TeamInfo(zh: "佛得角", flag: "🇨🇻"),
        "Congo DR": TeamInfo(zh: "刚果（金）", flag: "🇨🇩"),
        "Curaçao": TeamInfo(zh: "库拉索", flag: "🇨🇼"),
        "USA": TeamInfo(zh: "美国", flag: "🇺🇸"),
        "United States": TeamInfo(zh: "美国", flag: "🇺🇸"),
        "Mexico": TeamInfo(zh: "墨西哥", flag: "🇲🇽"),
        "Canada": TeamInfo(zh: "加拿大", flag: "🇨🇦"),
        "Argentina": TeamInfo(zh: "阿根廷", flag: "🇦🇷"),
        "Brazil": TeamInfo(zh: "巴西", flag: "🇧🇷"),
        "France": TeamInfo(zh: "法国", flag: "🇫🇷"),
        "England": TeamInfo(zh: "英格兰", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿"),
        "Spain": TeamInfo(zh: "西班牙", flag: "🇪🇸"),
        "Germany": TeamInfo(zh: "德国", flag: "🇩🇪"),
        "Portugal": TeamInfo(zh: "葡萄牙", flag: "🇵🇹"),
        "Netherlands": TeamInfo(zh: "荷兰", flag: "🇳🇱"),
        "Belgium": TeamInfo(zh: "比利时", flag: "🇧🇪"),
        "Croatia": TeamInfo(zh: "克罗地亚", flag: "🇭🇷"),
        "Italy": TeamInfo(zh: "意大利", flag: "🇮🇹"),
        "Uruguay": TeamInfo(zh: "乌拉圭", flag: "🇺🇾"),
        "Colombia": TeamInfo(zh: "哥伦比亚", flag: "🇨🇴"),
        "Japan": TeamInfo(zh: "日本", flag: "🇯🇵"),
        "South Korea": TeamInfo(zh: "韩国", flag: "🇰🇷"),
        "Korea Republic": TeamInfo(zh: "韩国", flag: "🇰🇷"),
        "Australia": TeamInfo(zh: "澳大利亚", flag: "🇦🇺"),
        "Morocco": TeamInfo(zh: "摩洛哥", flag: "🇲🇦"),
        "Senegal": TeamInfo(zh: "塞内加尔", flag: "🇸🇳"),
        "Switzerland": TeamInfo(zh: "瑞士", flag: "🇨🇭"),
        "Denmark": TeamInfo(zh: "丹麦", flag: "🇩🇰"),
        "Poland": TeamInfo(zh: "波兰", flag: "🇵🇱"),
        "Serbia": TeamInfo(zh: "塞尔维亚", flag: "🇷🇸"),
        "Austria": TeamInfo(zh: "奥地利", flag: "🇦🇹"),
        "Ukraine": TeamInfo(zh: "乌克兰", flag: "🇺🇦"),
        "Turkey": TeamInfo(zh: "土耳其", flag: "🇹🇷"),
        "Türkiye": TeamInfo(zh: "土耳其", flag: "🇹🇷"),
        "Sweden": TeamInfo(zh: "瑞典", flag: "🇸🇪"),
        "Wales": TeamInfo(zh: "威尔士", flag: "🏴󠁧󠁢󠁷󠁬󠁳󠁿"),
        "Scotland": TeamInfo(zh: "苏格兰", flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿"),
        "Czech Republic": TeamInfo(zh: "捷克", flag: "🇨🇿"),
        "Czechia": TeamInfo(zh: "捷克", flag: "🇨🇿"),
        "Norway": TeamInfo(zh: "挪威", flag: "🇳🇴"),
        "Nigeria": TeamInfo(zh: "尼日利亚", flag: "🇳🇬"),
        "Ghana": TeamInfo(zh: "加纳", flag: "🇬🇭"),
        "Cameroon": TeamInfo(zh: "喀麦隆", flag: "🇨🇲"),
        "Ivory Coast": TeamInfo(zh: "科特迪瓦", flag: "🇨🇮"),
        "Cote d'Ivoire": TeamInfo(zh: "科特迪瓦", flag: "🇨🇮"),
        "Egypt": TeamInfo(zh: "埃及", flag: "🇪🇬"),
        "Algeria": TeamInfo(zh: "阿尔及利亚", flag: "🇩🇿"),
        "Tunisia": TeamInfo(zh: "突尼斯", flag: "🇹🇳"),
        "South Africa": TeamInfo(zh: "南非", flag: "🇿🇦"),
        "Ecuador": TeamInfo(zh: "厄瓜多尔", flag: "🇪🇨"),
        "Peru": TeamInfo(zh: "秘鲁", flag: "🇵🇪"),
        "Chile": TeamInfo(zh: "智利", flag: "🇨🇱"),
        "Paraguay": TeamInfo(zh: "巴拉圭", flag: "🇵🇾"),
        "Venezuela": TeamInfo(zh: "委内瑞拉", flag: "🇻🇪"),
        "Bolivia": TeamInfo(zh: "玻利维亚", flag: "🇧🇴"),
        "Iran": TeamInfo(zh: "伊朗", flag: "🇮🇷"),
        "Saudi Arabia": TeamInfo(zh: "沙特", flag: "🇸🇦"),
        "Qatar": TeamInfo(zh: "卡塔尔", flag: "🇶🇦"),
        "Iraq": TeamInfo(zh: "伊拉克", flag: "🇮🇶"),
        "Jordan": TeamInfo(zh: "约旦", flag: "🇯🇴"),
        "United Arab Emirates": TeamInfo(zh: "阿联酋", flag: "🇦🇪"),
        "UAE": TeamInfo(zh: "阿联酋", flag: "🇦🇪"),
        "Uzbekistan": TeamInfo(zh: "乌兹别克斯坦", flag: "🇺🇿"),
        "China": TeamInfo(zh: "中国", flag: "🇨🇳"),
        "China PR": TeamInfo(zh: "中国", flag: "🇨🇳"),
        "New Zealand": TeamInfo(zh: "新西兰", flag: "🇳🇿"),
        "Costa Rica": TeamInfo(zh: "哥斯达黎加", flag: "🇨🇷"),
        "Panama": TeamInfo(zh: "巴拿马", flag: "🇵🇦"),
        "Jamaica": TeamInfo(zh: "牙买加", flag: "🇯🇲"),
        "Honduras": TeamInfo(zh: "洪都拉斯", flag: "🇭🇳"),
        "Haiti": TeamInfo(zh: "海地", flag: "🇭🇹"),
        "Bosnia-Herzegovina": TeamInfo(zh: "波黑", flag: "🇧🇦"),
        "Greece": TeamInfo(zh: "希腊", flag: "🇬🇷"),
        "Hungary": TeamInfo(zh: "匈牙利", flag: "🇭🇺"),
        "Romania": TeamInfo(zh: "罗马尼亚", flag: "🇷🇴"),
        "Slovakia": TeamInfo(zh: "斯洛伐克", flag: "🇸🇰"),
        "Slovenia": TeamInfo(zh: "斯洛文尼亚", flag: "🇸🇮"),
        "Cape Verde": TeamInfo(zh: "佛得角", flag: "🇨🇻"),
        "Mali": TeamInfo(zh: "马里", flag: "🇲🇱"),
        "Burkina Faso": TeamInfo(zh: "布基纳法索", flag: "🇧🇫"),
        "Angola": TeamInfo(zh: "安哥拉", flag: "🇦🇴"),
        "Curacao": TeamInfo(zh: "库拉索", flag: "🇨🇼"),
        "Suriname": TeamInfo(zh: "苏里南", flag: "🇸🇷"),
        "Indonesia": TeamInfo(zh: "印度尼西亚", flag: "🇮🇩"),
        "Republic of Ireland": TeamInfo(zh: "爱尔兰", flag: "🇮🇪"),
        "Ireland": TeamInfo(zh: "爱尔兰", flag: "🇮🇪"),
    ]
}
